server:
  port: 8080
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 120

spring:
  application:
    name: eureka_server_qa

eureka:
  instance:
    preferIpAddress: true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.191.86:8080/eureka/
  server:
    enable-self-preservation: false
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 60000
    #eviction-interval-timer-in-ms: 3000
 
 management:
  security:
    enabled: false
