eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.191.86:8888/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3

server:
  port: 7777
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 110
spring:
  application:
    name: zuul_server

zuul:
  routes:
    api-a:
      path: /7777/**
      serviceId: order_server
    api-b:
      path: /1111/**
      serviceId: stock_service
      
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 1000    

#logging:  
#  config: /data/cloud/zuul/logback.xml
#  file: /data/nginx_log/cloud/zuul.log

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxTotalConnections: 1000
  MaxConnectionsPerHost: 1000

management:
  security:
    enabled: false
 
